### ISSUE TITLE
0v reports 256% charge

### ISSUE THREAD

**Issue by dotMorten** [sparkfun/SparkFun_MAX1704x_Fuel_Gauge_Arduino_Library#3] opened 2021-09-19 15:19 UTC
Was reading the voltage and percentage, and one reading was completely off, leading to this result:
```c
  voltage = lipo.getVoltage();
  soc = lipo.getSOC();
  Serial.println("Battery Voltage = " + String(voltage) + " (" + String(soc) + "%)");
```
output:
```
08:16:44.717 -> Battery Voltage = 4.17 (97.98%)
08:16:45.739 -> Battery Voltage = 4.17 (97.98%)
08:16:46.711 -> Battery Voltage = 4.17 (97.98%)
08:16:48.706 -> Battery Voltage = 0.00 (256.00%)
08:16:49.727 -> Battery Voltage = 4.17 (97.98%)
08:16:50.748 -> Battery Voltage = 4.17 (97.98%)
```

Looks like there's a bug where 0v equates to 256% instead of 0%.

**Comment by PaulZC** [comment] 2021-09-20 06:15
Hi Morten (@dotMorten ),

Thanks for reporting this.

Looking at the ```getSOC``` code:

```
  uint16_t soc;
  float percent;
  soc = read16(MAX17043_SOC);
  percent = (float)((soc & 0xFF00) >> 8);
  percent += ((float)(soc & 0x00FF)) / 256.0;
```

The only way percent can be 256% is if soc is 0xFFFF. Which is clearly invalid... And also very weird since ```read16``` will return 0x000, not 0xFFFF, if the I2C transmission fails.

```getVoltage``` uses a completely separate I2C transmission ( ```vCell = read16(MAX17043_VCELL);``` ).

Best guess, the MAX1704n was having a momentary bad day, or there was a drop in I2C communication?

I can 'fix' this by checking for soc == 0xFFFF and then returning zero %. But maybe it is better to leave the code as-is? 256% is more obviously wrong. The battery could legitimately report zero % when depleted.

Does this happen often? It would be really useful to be able to see the debug messages around this. Could you repeat with ```lipo.enableDebugging();``` enabled?

Very best wishes,
Paul

**Comment by dotMorten** [comment] 2021-09-20 13:35
Thanks for this analysis. Yesterday I also observed a momentary 5.12v which also resulted in 256%.

**Comment by PaulZC** [comment] 2021-10-19 09:36
Hi Morten (@dotMorten ),

[Another customer](https://forum.sparkfun.com/viewtopic.php?p=229068#p229068) has noticed the same behavior as you.

I should have asked you earlier:
- Which fuel gauge board are you using? The SparkX (Black) Qwiic Fuel Gauge, or the SparkFun (Red) LiPo Fuel Gauge?
- Which processor board are you using?
- Do you have any other devices connected to the I2C bus?

Thanks!
Paul

**Comment by dotMorten** [comment] 2021-10-22 16:18
> Which fuel gauge board are you using

Whichever is on the black `SparkX Thing Plus C - ESP32 WROOM`

> Do you have any other devices connected to the I2C bus?

Yes `NEO-M9N` GPS on QWIIC and a small 2.9" e-paper display on SPI

**Comment by PaulZC** [comment] 2021-10-23 10:15
Hi Morten,

Ah, that all makes sense. I think you are seeing the exact same thing as the customer on the forum. He noticed the same occasional bus errors as you, also on the Thing Plus C, and noticed that they went away when he had another device connected to the I2C bus. That device had pull-up resistors on it.

In your case, I'm guessing you have opened the I2C pull-up resistor jumpers on the NEO-M9N board?

In summary, the root cause is that - on their own - the internal pull-up resistors on the ESP32 pins are not quite strong enough for the MAX17048 and so you see occasional bus errors. The fix is to add some additional resistors to increase the pull-up strength. But that's not going to work for you as that would almost certainly re-introduce errors in the NEO-M9N data...

I suspect having occasional errors in the fuel gauge readings is the lesser of the two evils in your case?

Very best wishes,
Paul

**Comment by PaulZC** [comment] 2022-12-15 21:40
Hi @dotMorten ,

I’m closing this… The 256% issue with the ESP was due to a lack of pull-up resistors on the I2C bus. With pull-ups, the issue goes away.

Hope you’re doing ok.
Very best wishes,
Paul

**Closed as completed by PaulZC** 2022-12-15 21:40 UTC
